
stages:
- test
- build_image
- push_image

.merge_main:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_PIPELINE_SOURCE == "push"

.request_main:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_PIPELINE_SOURCE == "merge_request_event"



build_image:
  stage: build_image
  image: docker:20.10.12-dind-alpine3.15
  rules:
    - !reference [.merge_main, rules]
  script: "docker build -t registry.gitlab.com/leetcyber/leet-app:latest ."


push_image:
  stage: push_image
  image: docker:20.10.12-dind-alpine3.15
  rules:
    - !reference [.merge_main, rules]
  script: 
    - "docker login registry.gitlab.com -u patrickbreen -p ${CI_JOB_TOKEN}"
    - "docker push registry.gitlab.com/leetcyber/leet-app:latest"
